# Generated by Django 3.0.8 on 2021-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=10)),
                ('visitor', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
