# Generated by Django 3.0.8 on 2021-01-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='place',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='local',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='match',
            name='visitor',
            field=models.CharField(max_length=15),
        ),
    ]
