# Generated by Django 3.0.8 on 2021-01-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0002_auto_20210102_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='local_img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='match',
            name='visitor_img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
