# Generated by Django 3.0.8 on 2021-01-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0003_auto_20210122_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='local_img',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='match',
            name='visitor_img',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
    ]
