# Generated by Django 3.0.8 on 2021-01-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0004_auto_20210122_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='visitor_img',
            field=models.URLField(default=''),
        ),
    ]
